config/routes.rb
Rails.application.routes.draw do
  resources :weathers, only: %i[index] do
    get 'search', on: :collection
  end
  resources :forecasts, only: %i[index] do
    get 'search', on: :collection
  end
  root to: 'weathers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_req_url, only: %i[index search]

  def index
    response = @conn.get do |req|
      req.url '/data/2.5/forecast'
      req.params[:q] = 'Shibuya,jp'
      req.params[:units] = 'metric'
      req.params[:APPID] = Rails.application.credentials.openweathermap[:api_key]
      req.params[:lang] = 'ja'
    end
    @name = '渋谷'
    @result = JSON.parse(response.body)
    render :index
  end

  def search
    response = @conn.get do |req|
      req.url '/data/2.5/forecast'
      req.params[:q] = "#{params[:search][:prefectures]},jp"
      req.params[:units] = 'metric'
      req.params[:APPID] = Rails.application.credentials.openweathermap[:api_key]
      req.params[:lang] = 'ja'
    end
    @result = JSON.parse(response.body)
    name = SearchForm::SEARCH_KEY.select { |k| k.second == @result['city']['name'].downcase }
    @name = name.shift.first
    render :index
  end

  private

  def set_req_url
    @conn = Faraday.new(:url => 'https://api.openweathermap.org') do |builder|
      builder.request :url_encoded
      builder.response :logger
      builder.adapter :net_http
    end
  end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_req_url, only: %i[index search]

  def index
    if params[:lat].present?
      response = @conn.get do |req|
        req.url '/data/2.5/weather'
        req.params[:lat] = params[:lat].to_f
        req.params[:lon] = params[:lon].to_f
        req.params[:units] = 'metric'
        req.params[:APPID] = Rails.application.credentials.openweathermap[:api_key]
        req.params[:lang] = 'ja'
      end
    else
      response = @conn.get do |req|
        req.url '/data/2.5/weather'
        req.params[:q] = 'Shibuya,jp'
        req.params[:units] = 'metric'
        req.params[:APPID] = Rails.application.credentials.openweathermap[:api_key]
        req.params[:lang] = 'ja'
      end
    end
    @name = params[:lat].present? ? '現在地' : '渋谷'
    @result = JSON.parse(response.body)
    # binding.pry
    render partial: 'result' if params[:lat].present?
  end

  def search
    response = @conn.get do |req|
      req.url '/data/2.5/weather'
      req.params[:q] = "#{params[:search][:prefectures]},jp"
      req.params[:units] = 'metric'
      req.params[:APPID] = Rails.application.credentials.openweathermap[:api_key]
      req.params[:lang] = 'ja'
    end
    @result = JSON.parse(response.body)
    name = SearchForm::SEARCH_KEY.select { |k| k.second == @result['name'].downcase }
    @name = name.shift.first
    render :index
  end

  private

  def set_req_url
    @conn = Faraday.new(:url => 'https://api.openweathermap.org') do |builder|
      builder.request :url_encoded
      builder.response :logger
      builder.adapter :net_http
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forecasts/_result.html.erb
<div class='result_header'>
  <%= @name %>のお天気予報（<%= Time.now.strftime('%Y年%m月%d日 %H時%M分%S秒') %> 現在）
</div>
<div class='result_body'>
  <% @result['list'].each do |result| %>
    <p>
      &emsp;日時: <%= result['dt_txt'].to_datetime.strftime('%m/%d %H:00') %>,
      &emsp;天気: <%= result['weather'][0]['description'] %>,
      &emsp;気温: <%= result['main']['temp'].to_s %>℃,
      &emsp;湿度: <%= result['main']['humidity'].to_s %>％
    </p>
  <% end %>
</div>

app/views/forecasts/index.html.erb
<h1>お天気予報&nbsp;<small><%= link_to 'お天気情報はこちら', weathers_path %></small></h1>
<div class='col-xs-4'>
  <div class='form row'>
    <%= simple_form_for :search, url: search_forecasts_path, method: :get do |f| %>
      <div class='form_input col-xs-6'>
        <%= f.input :prefectures,
                    as: :select,
                    input_html: { class: 'form-controll input-lg' },
                    include_blank: false,
                    label: false,
                    selected: @result['city']['name'].downcase,
                    collection: SearchForm::SEARCH_KEY %>
      </div>
      <div class='form_btn col-xs-6'>
        <%= f.button :submit, '検索', class: 'btn btn-info btn-lg' %>
      </div>
    <% end %>
  </div>
</div>
<div class='col-xs-8'>
  <div id='result'><%= render partial: 'result' %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <div class='row'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/weathers/_result.html.erb
<div class='result_header'>
  <%= @name %>のお天気（<%= Time.now.strftime('%Y年%m月%d日 %H時%M分%S秒') %> 現在）
</div>
<div class='result_body'>
  <p>&emsp;天気：<%= @result['weather'][0]['description'] %></p>
  <p>&emsp;気温：<%= @result['main']['temp'].to_s %>℃</p>
  <p>&emsp;湿度：<%= @result['main']['humidity'].to_s %>％</p>
  <p>&emsp;日の出：<%= Time.at(@result['sys']['sunrise']).strftime('%H時%M分%S秒') %></p>
  <p>&emsp;日の入：<%= Time.at(@result['sys']['sunset']).strftime('%H時%M分%S秒') %></p>
</div>

app/views/weathers/index.html.erb
<script type="text/javascript">
  var lat;
  var lon;

  if( navigator.geolocation ) {
    navigator.geolocation.getCurrentPosition(success, error);
    function success(position) {
      var data = position.coords;
      lat = data.latitude;
      lon = data.longitude;
    }
    function error(error) {
      alert("位置情報を取得できません");
    }
  } else {
    alert("あなたのブラウザでは位置情報が取得できません");
  }

  setInterval("ajaxGet()", 100000);
  function ajaxGet()
  {
    var hostUrl= "<%= weathers_path %>";
    $.ajax({
      url: hostUrl,
      type: 'GET',
      dataType: 'html',
      data: {
        lat: lat,
        lon: lon
      },
    }).done(function (data) {
      console.log("ok");
      $('#result').empty().append(data);
    }).fail(function (data) {
      console.log("error");
    });
  }
</script>

<h1>お天気情報&nbsp;<small><%= link_to 'お天気予報はこちら', forecasts_path %></small></h1>
<div class='col-xs-4'>
  <div class='form row'>
    <%= simple_form_for :search, url: search_weathers_path, method: :get do |f| %>
      <div class='form_input col-xs-6'>
        <%= f.input :prefectures,
                    as: :select,
                    input_html: { class: 'form-controll input-lg' },
                    include_blank: false,
                    label: false,
                    selected: @result['name'].downcase,
                    collection: SearchForm::SEARCH_KEY %>
      </div>
      <div class='form_btn col-xs-6'>
        <%= f.button :submit, '検索', class: 'btn btn-info btn-lg' %>
      </div>
    <% end %>
  </div>
</div>
<div class='col-xs-8'>
  <div id='result'><%= render partial: 'result' %></div>
</div>